### ISSUE TITLE
elvish.kak is missing

### ISSUE THREAD

**Issue by bensleveritt** [elves/awesome-elvish#19]
Looks like the repo for elvish.kak is gone. Not sure if there's a backup somewhere, or if it's being maintained.

**Comment by Wizhi** [comment]
I was just looking for it as well - it was [seemingly moved to GitLab][gitlab], but this has since then been removed as well.

I haven't been able to track down any other mirrors from @notramo, so I'd assume they're not interested in maintaining it.

[gitlab]: https://gitlab.com/notramo/elvish.kak

**Comment by notramo** [comment]
The repo is moved to https://git.tchncs.de/notramo/elvish.kak

**Comment by bensleveritt** [comment]
Thanks for the update @notramo
